CC      = g++
CFLAGS = -g `pkg-config --cflags opencv`
TARGET1 = objects
OBJS1   = objects.o
LIBS    = `pkg-config --libs opencv`

all: $(TARGET1)

$(TARGET1): $(OBJS1)
        $(CC) -o $@ $(OBJS1) $(LIBS)

.SUFFIXES: .c .o

.c.o:
        $(CC) -c $(CFLAGS) $<

.PHONY: clean

clean:
        /bin/rm -f core *.o $(TARGET1)
