CREATE DATABASE IF NOT EXISTS enterprise DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_unicode_ci';

USE enterprise;

CREATE TABLE USERS (
    USERS_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    FIRSTNAME  VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    LASTUPDATED DATE,
    PRIMARY KEY(USERS_ID)
) ENGINE = InnoDB;